### ISSUE TITLE
Biotransformer v3.0 update

### ISSUE THREAD

**Issue by fgiacomoni** [martenson/biotransformer-snapshots#1]
Hi Martin,
I started a new recipe on Biotransformer when I saw your contribution on bioconda.
Do you plan to update your recipe on the 3.0 version ?
the Wishart lab github proposes a full new version at: https://github.com/Wishartlab-openscience/Biotransformer
Thank you for all
Yours,

**Comment by martenson** [comment]
Hey @fgiacomoni, I am sorry to miss this issue. We've updated to 3.0 recently, links:

https://github.com/RECETOX/galaxytools/tree/master/tools/biotransformer
https://bioconda.github.io/recipes/biotransformer/README.html

**Comment by fgiacomoni** [comment]
Good news ! Thank you for your work.
